CREATE DATABASE IF NOT EXISTS task_manager;
USE task_manager;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(150) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR(50) DEFAULT 'Study',
  priority ENUM('Low', 'Medium', 'High') DEFAULT 'Medium',
  status ENUM('Pending', 'In Progress', 'Completed') DEFAULT 'Pending',
  due_date DATE NOT NULL,
  reminder_at DATETIME NULL,
  completed_at DATETIME NULL,
  pinned TINYINT(1) DEFAULT 0,
  favorite TINYINT(1) DEFAULT 0,
  attachment_name VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_tasks_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE tasks MODIFY status ENUM('Pending', 'In Progress', 'Completed') DEFAULT 'Pending';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS reminder_at DATETIME NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS completed_at DATETIME NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS pinned TINYINT(1) DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS favorite TINYINT(1) DEFAULT 0;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS attachment_name VARCHAR(255) NULL;
